name: Deploy to QA

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy-qa:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to QA
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Tabular Editor\TabularEditor.exe" `
            "${{ github.workspace }}\Model.bim" `
            -deploy localhost `
            "${{ secrets.QA_DB_NAME }}" `
            -O -C -P
          if ($LASTEXITCODE -ne 0) { exit 1 }
          Write-Host "Deploy a QA exitoso"