name: Deploy to QA

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy-qa:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar ruta
        shell: powershell
        run: |
          Get-ChildItem "C:\Windows\System32\actions-runner\_work\" -Recurse -Filter "Model.bim" | Select-Object FullName


      - name: Deploy to QA
        shell: powershell
        run: |
          $te = "C:\Program Files (x86)\Tabular Editor\TabularEditor.exe"
          $db = "${{ secrets.QA_DB_NAME }}"
          $model = "$env:GITHUB_WORKSPACE\Model.bim"
          if (!(Test-Path $model)) {
            Write-Host "No encontrado en: $model"
            exit 1
          }
          Write-Host "Modelo encontrado en: $model"
          & $te $model -deploy localhost $db -O -C -P
          if ($LASTEXITCODE -ne 0) { exit 1 }